# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#

"""Generate macros.py from environment variables. Run after setting env vars from Readme.md."""

import os
import sys

REQUIRED = ["JEPAWM_DSET", "JEPAWM_LOGS", "JEPAWM_HOME"]
OPTIONAL = ["JEPAWM_OSSCKPT", "JEPAWM_CKPT"]

missing = [v for v in REQUIRED if not os.environ.get(v)]
if missing:
    sys.exit(f"Error: Missing env vars: {', '.join(missing)}\nSet them with: export VAR=/path")

script_dir = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(script_dir, "macros.py"), "w") as f:
    f.write("# Auto-generated by setup_macros.py - DO NOT COMMIT\n")
    for var in REQUIRED + OPTIONAL:
        if val := os.environ.get(var):
            f.write(f'{var} = "{val}"\n')

print("Created macros.py with:", ", ".join(v for v in REQUIRED + OPTIONAL if os.environ.get(v)))
